.\"     Title: pam_env
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 01/08/2008
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"
.TH "PAM_ENV" "8" "01/08/2008" "Linux-PAM Manual" "Linux-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_env - PAM module to set/unset environment variables
.SH "SYNOPSIS"
.HP 11
\fBpam_env\.so\fR [debug] [conffile=\fIconf\-file\fR] [envfile=\fIenv\-file\fR] [readenv=\fI0|1\fR]
.SH "DESCRIPTION"
.PP
The pam_env PAM module allows the (un)setting of environment variables\. Supported is the use of previously set environment variables as well as
\fIPAM_ITEM\fRs such as
\fIPAM_RHOST\fR\.
.PP
By default rules for (un)setting of variables is taken from the config file
\fI/etc/security/pam_env\.conf\fR
if no other file is specified\.
.PP
This module can also parse a file with simple
\fIKEY=VAL\fR
pairs on seperate lines (\fI/etc/environment\fR
by default)\. You can change the default file to parse, with the
\fIenvfile\fR
flag and turn it on or off by setting the
\fIreadenv\fR
flag to 1 or 0 respectively\.
.SH "OPTIONS"
.PP
\fBconffile=\fR\fB\fI/path/to/pam_env\.conf\fR\fR
.RS 4
Indicate an alternative
\fIpam_env\.conf\fR
style configuration file to override the default\. This can be useful when different services need different environments\.
.RE
.PP
\fBdebug\fR
.RS 4
A lot of debug informations are printed with
\fBsyslog\fR(3)\.
.RE
.PP
\fBenvfile=\fR\fB\fI/path/to/environment\fR\fR
.RS 4
Indicate an alternative
\fIenvironment\fR
file to override the default\. This can be useful when different services need different environments\.
.RE
.PP
\fBreadenv=\fR\fB\fI0|1\fR\fR
.RS 4
Turns on or off the reading of the file specified by envfile (0 is off, 1 is on)\. By default this option is on\.
.RE
.SH "MODULE SERVICES PROVIDED"
.PP
The
\fBauth\fR
and
\fBsession\fR
services are supported\.
.SH "RETURN VALUES"
.PP
PAM_ABORT
.RS 4
Not all relevant data or options could be gotten\.
.RE
.PP
PAM_BUF_ERR
.RS 4
Memory buffer error\.
.RE
.PP
PAM_IGNORE
.RS 4
No pam_env\.conf and environment file was found\.
.RE
.PP
PAM_SUCCESS
.RS 4
Environment variables were set\.
.RE
.SH "FILES"
.PP
\fI/etc/security/pam_env\.conf\fR
.RS 4
Default configuration file
.RE
.PP
\fI/etc/environment\fR
.RS 4
Default environment file
.RE
.SH "SEE ALSO"
.PP

\fBpam_env.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)\.
.SH "AUTHOR"
.PP
pam_env was written by Dave Kinchlea <kinch@kinch\.ark\.com>\.
