.\"     Title: unix_update
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 04/16/2008
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"
.TH "UNIX_UPDATE" "8" "04/16/2008" "Linux-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
unix_update - Helper binary that updates the password of a given user
.SH "SYNOPSIS"
.HP 12
\fBunix_update\fR [\.\.\.]
.SH "DESCRIPTION"
.PP

\fIunix_update\fR
is a helper program for the
\fIpam_unix\fR
module that updates the password of a given user\. It is not intended to be run directly from the command line and logs a security violation if done so\.
.PP
The purpose of the helper is to enable tighter confinement of login and password changing services\. The helper is thus called only when SELinux is enabled and in the enforcing mode on the system\.
.PP
The interface of the helper \- command line options, and input/output data format are internal to the
\fIpam_unix\fR
module and it should not be called directly from applications\.
.SH "SEE ALSO"
.PP

\fBpam_unix\fR(8)
.SH "AUTHOR"
.PP
Written by Tomas Mraz and other various people\.
