#
# $Id: Makefile,v 1.1 2004/09/24 11:42:39 kukuk Exp $
#
# This Makefile controls a build process of $(TITLE) module for
# Linux-PAM. You should not modify this Makefile (unless you know
# what you are doing!).
#
# Created by Andrew Morgan <morgan@linux.kernel.org> 2000/08/27
#

include ../../Make.Rules

TITLE=pam_succeed_if
MAN8=$(TITLE).8

include ../Simple.Rules
