.\"     Title: pam_close_session
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 04/16/2008
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"
.TH "PAM_CLOSE_SESSION" "3" "04/16/2008" "Linux-PAM Manual" "Linux-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_close_session - terminate PAM session management
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_appl\.h>
.fi
.ft
.HP 22
.BI "int pam_close_session(pam_handle_t\ *" "pamh" ", int\ " "flags" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_close_session\fR
function is used to indicate that an authenticated session has ended\. The session should have been created with a call to
\fBpam_open_session\fR(3)\.
.PP
It should be noted that the effective uid,
\fBgeteuid\fR(2)\. of the application should be of sufficient privilege to perform such tasks as unmounting the user\'s home directory for example\.
.PP
The flags argument is the binary or of zero or more of the following values:
.PP
PAM_SILENT
.RS 4
Do not emit any messages\.
.RE
.SH "RETURN VALUES"
.PP
PAM_ABORT
.RS 4
General failure\.
.RE
.PP
PAM_BUF_ERR
.RS 4
Memory buffer error\.
.RE
.PP
PAM_SESSION_ERR
.RS 4
Session failure\.
.RE
.PP
PAM_SUCCESS
.RS 4
Session was successful terminated\.
.RE
.SH "SEE ALSO"
.PP

\fBpam_open_session\fR(3),
\fBpam_strerror\fR(3)
