# $Id: Makefile,v 1.1 2004/09/24 11:49:37 kukuk Exp $
#
# This Makefile controls a build process of $(TITLE) module for
# Linux-PAM. You should not modify this Makefile (unless you know
# what you are doing!).
#
#

include ../../Make.Rules

TITLE=pam_localuser
MAN8=pam_localuser.8

include ../Simple.Rules
